//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UygulamaOdevi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFERENCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONFERENCE()
        {
            this.CONFERENCE_TAGS = new HashSet<CONFERENCE_TAGS>();
            this.SUBMISSIONS = new HashSet<SUBMISSIONS>();
        }
    
        public string ConfID { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> Submission_Deadline { get; set; }
        public Nullable<int> CreatorUser { get; set; }
        public string WebSite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONFERENCE_TAGS> CONFERENCE_TAGS { get; set; }
        public virtual USERS USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBMISSIONS> SUBMISSIONS { get; set; }
    }
}
