//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UygulamaOdevi2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KONFERANSEntities : DbContext
    {
        public KONFERANSEntities()
            : base("name=KONFERANSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONFERENCE> CONFERENCE { get; set; }
        public virtual DbSet<CONFERENCE_TAGS> CONFERENCE_TAGS { get; set; }
        public virtual DbSet<COUNTRY> COUNTRY { get; set; }
        public virtual DbSet<COUNTRY_CITY> COUNTRY_CITY { get; set; }
        public virtual DbSet<SUBMISSIONS> SUBMISSIONS { get; set; }
        public virtual DbSet<USER_INFO> USER_INFO { get; set; }
        public virtual DbSet<USER_LOG> USER_LOG { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
