//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UygulamaOdevi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBMISSIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBMISSIONS()
        {
            this.SUBMISSIONS1 = new HashSet<SUBMISSIONS>();
        }
    
        public Nullable<int> AuthenticationID { get; set; }
        public string ConfID { get; set; }
        public int SubmissionID { get; set; }
        public Nullable<int> prevSubmissionID { get; set; }
    
        public virtual CONFERENCE CONFERENCE { get; set; }
        public virtual USERS USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBMISSIONS> SUBMISSIONS1 { get; set; }
        public virtual SUBMISSIONS SUBMISSIONS2 { get; set; }
    }
}
