//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UygulamaOdevi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_INFO
    {
        public int InfoID { get; set; }
        public string Salutation { get; set; }
        public Nullable<int> AuthenticationID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Affiliation { get; set; }
        public string primary_email { get; set; }
        public string secondary_email { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string URL { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> Record_Creation_Date { get; set; }
    
        public virtual COUNTRY COUNTRY1 { get; set; }
        public virtual COUNTRY_CITY COUNTRY_CITY { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
